# Generated by Django 4.2 on 2025-06-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Конкретные права для этого пользователя', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='Права доступа'),
        ),
    ]
